routes/web.php
<?php

use App\Http\Controllers\CommentController;
use App\Http\Controllers\CarouselController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ColorController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WelcomeController;
use Illuminate\Support\Facades\Route;

// http verb: get, post, put/patch, delete

Route::get('/', [WelcomeController::class, 'welcome']);
Route::get('/caterories/{category}/products', [WelcomeController::class, 'productList'])->name('frontend.products');

Route::get('/products/{product}', [WelcomeController::class, 'productDetails'])->name('frontend.products.show');

Route::get('/my-shopping-cart', [WelcomeController::class, 'shoppingCart'])->name('frontend.cart');

require __DIR__ . '/auth.php';
Route::middleware('auth')->prefix('dashboard')->group(function(){



    Route::post('/products/{product}/comments', [CommentController::class, 'store'])->name('products.comments.store');



    Route::get('/', function () {
        return view('home');
    });
    Route::get('carousels-trash', [CarouselController::class, 'trash'])->name('carousels.trash');
    Route::patch('carousels-trash/{id}', [CarouselController::class, 'restore'])->name('carousels.restore');
    Route::delete('carousels-trash/{id}', [CarouselController::class, 'delete'])->name('carousels.delete');
    Route::resource('carousels', CarouselController::class);

    Route::get('/categories-trash', [CategoryController::class, 'trash'])->name('categories.trash');
    Route::get('/categories/{id}/restore', [CategoryController::class, 'restore'])->name('categories.restore');
    Route::delete('/categories/{id}/delete', [CategoryController::class, 'delete'])->name('categories.delete');
    Route::get('/categories/pdf', [CategoryController::class, 'downloadPdf'])->name('categories.pdf');

    Route::resource('categories', CategoryController::class);

    Route::get('/colors-trash', [ColorController::class, 'trash'])->name('colors.trash');
    Route::get('/colors/{id}/restore', [ColorController::class, 'restore'])->name('colors.restore');
    Route::delete('/colors/{id}/delete', [ColorController::class, 'delete'])->name('colors.delete');
    Route::get('/colors/pdf', [ColorController::class, 'downloadPdf'])->name('colors.pdf');
    Route::resource('colors', ColorController::class);


    Route::get('/products-trash', [ProductController::class, 'trash'])->name('products.trash');
    Route::get('/products/{id}/restore', [ProductController::class, 'restore'])->name('products.restore');
    Route::delete('/products/{id}/delete', [ProductController::class, 'delete'])->name('products.delete');
    Route::get('/products/pdf', [ProductController::class, 'downloadPdf'])->name('products.pdf');
    Route::resource('products', ProductController::class);

    Route::prefix('users')->group(function () {
        Route::get('/', [UserController::class, 'index'])->name('users.index');
        Route::get('/{user}', [UserController::class, 'show'])->name('users.show');
        Route::get('/{user}/change-role', [UserController::class, 'changeRole'])->name('users.change_role');
        Route::patch('/{user}/change-role', [UserController::class, 'updateRole'])->name('users.update_role');
    });

    Route::post('products/{product}/cart', [CartController::class, 'store'])->name('products.cart.store');
});

Route::redirect('/here', '/users');

Route::fallback(function () {
    echo 'Apnar url thik nai';
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = ['title', 'is_active', 'image'];
    
    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Image;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Database\QueryException;

class CategoryController extends Controller
{
    
    public function index()
    {
        $categories = Category::all();
        return view('categories.index', compact('categories'));
    }

    public function create()
    {
        return view('categories.create');
    }

    public function show(Category $category)
    {
        // $category = Category::find($id);
        return view('categories.show', compact('category'));
    }

    public function store(CategoryRequest $request)
    {
        $requestData = [
            'title' => $request->title,
            'is_active' => $request->is_active ? true : false,
            'image' => $this->uploadImage($request->file('image'))
        ];

        Category::create($requestData);

        return redirect()
            ->route('categories.index')
            ->withMessage('Successfully Created');
    }

    public function edit(Category $category)
    {
        // $category = Category::find($id);
        return view('categories.edit', compact('category'));
    }

    public function update(CategoryRequest $request, Category $category)
    {
        // $category = Category::find($id);

        $requestData = [
            'title' => $request->title,
            'is_active' => $request->is_active ? true : false,
        ];

        if ($request->hasFile('image')) {
            $requestData['image'] = $this->uploadImage($request->file('image'));
        }

        $category->update($requestData);

        return redirect()
            ->route('categories.index')
            ->withMessage('Successfully Updated');
    }

    public function downloadPdf()
    {
        $categories = Category::all();
        $pdf = Pdf::loadView('categories.pdf', compact('categories'));
        return $pdf->download('category-list.pdf');
    }

    public function destroy(Category $category)
    {
        // $category = Category::find($id);
        $category->delete();

        // Session::flash('message', 'Successfully deleted');
        // return redirect()
        //         ->route('categories.index')
        //         ->with('message', 'Successfully deleted');

        return redirect()
            ->route('categories.index')
            ->withMessage('Successfully deleted');
    }

    public function trash()
    {
        $categories = Category::onlyTrashed()->get();
        return view('categories.trash', compact('categories'));
    }

    public function restore($id)
    {
        $category = Category::onlyTrashed()->find($id);
        $category->restore();

        return redirect()
            ->route('categories.trash')
            ->withMessage('Successfully restored');
    }

    public function delete($id)
    {
        try {
            $category = Category::onlyTrashed()->find($id);
            $category->forceDelete();

            return redirect()
                ->route('categories.trash')
                ->withMessage('Successfully deleted');
        } catch (QueryException $e) {
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    public function uploadImage($image)
    {
        $originalName = $image->getClientOriginalName();
        $fileName = date('Y-m-d') . time() . $originalName;

        // $image->move(storage_path('/app/public/categories'), $fileName); 

        Image::make($image)
            ->resize(200, 200)
            ->save(storage_path() . '/app/public/categories/' . $fileName);

        return $fileName;
    }

}

resources/views/categories/create.blade.php
<x-master>
    <x-slot:title>
        Category Create
        </x-slot>

        @if(session('message'))
        <span class="text-success">{{ session('message') }}</span>
        @endif

        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Categories</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <a href="{{ route('categories.index') }}">
                    <button type="button" class="btn btn-sm btn-outline-info">
                        <span data-feather="list"></span>
                        List
                    </button>
                </a>
            </div>
        </div>

        <x-forms.errors />

        <form 
            action="{{ route('categories.store') }}" 
            method="post" 
            enctype="multipart/form-data">

            @csrf

            <x-forms.input 
                type="text" 
                name="title" 
                placeholder="Enter title" 
                required
                label="Title"
                />

            <x-forms.input type="file" name="image" label='Picture' />

            @php
                $checklist = ['Is Active'];
            @endphp

            <x-forms.checkbox :checklist="$checklist" />

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

</x-master>

resources/views/categories/edit.blade.php
<x-master>
    <x-slot:title>
        Category Create
        </x-slot>

        @if(session('message'))
        <span class="text-success">{{ session('message') }}</span>
        @endif

        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Categories</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <a href="{{ route('categories.index') }}">
                    <button type="button" class="btn btn-sm btn-outline-info">
                        <span data-feather="list"></span>
                        List
                    </button>
                </a>
            </div>
        </div>

        <x-forms.errors />
        
        <form action="{{ route('categories.update', $category->id) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('patch')

            <x-forms.input 
                type="text" 
                name="title" 
                :value="old('title', $category->title)"
                placeholder="Enter title" 
                required 
            />

            <img src="{{ asset('storage/categories/'.$category->image) }}" height="250" />

            <x-forms.input type="file" name="image" label='Picture' />

            @php
                $checklist = ['Is Active ?'];

                if($category->is_active){
                    $checkedItems = [0];
                } else {
                    $checkedItems = [];
                }
            @endphp

            <x-forms.checkbox :checklist="$checklist" :checkedItems="$checkedItems" />

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

</x-master>

resources/views/categories/index.blade.php
<x-master>
    <x-slot:title>
        Category List
    </x-slot>

    <x-forms.message />
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Categories</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <a href="{{ route('categories.pdf') }}">
                <button type="button" class="btn btn-sm btn-outline-secondary">PDF</button>
                </a>
                <button type="button" class="btn btn-sm btn-outline-secondary">Excel</button>
                <a href="{{ route('categories.trash') }}">
                    <button type="button" class="btn btn-sm btn-outline-danger">Trash</button>
                </a>
            </div>
            <a href="{{ route('categories.create') }}">
                <button type="button" class="btn btn-sm btn-outline-primary">
                    <span data-feather="plus"></span>
                    Add New
                </button>
            </a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>SL#</th>
                <th>Title</th>
                <th width="180">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach($categories as $category)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $category->title }}</td>
                <td>
                    <a class="btn btn-sm btn-info" href="{{ route('categories.show', $category->id) }}">Show</a>
                    <a class="btn btn-sm btn-warning" href="{{ route('categories.edit', $category->id) }}">Edit</a>
                    <form action="{{ route('categories.destroy', $category->id) }}" method="post" style="display:inline">
                        @csrf
                        @method('delete')
                        <button class="btn btn-sm btn-danger" onclick="return confirm('Are you sure want to delete')">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</x-master>

resources/views/categories/pdf.blade.php
<table>
    <thead>
        <tr>
            <th>SL#</th>
            <th>Title</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach($categories as $category)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $category->title }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

resources/views/categories/show.blade.php
<x-master>
    <x-slot:title>
        Category Details
    </x-slot>
    
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Categories</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="{{ route('categories.index') }}">
                <button type="button" class="btn btn-sm btn-outline-primary">
                    <span data-feather="list"></span>
                    List
                </button>
            </a>
        </div>
    </div>

    <h1>Title: {{ $category->title }}</h1>

    <img src="{{ asset('storage/categories/'.$category->image) }}" />

    <p>Is Active ?: {{ $category->is_active ? 'Yes' : 'No' }}</p>
    
    <h1>Products</h1>
    <hr>
    <table class="table">
        <thead>
            <tr>
                <th>SL#</th>
                <th>Title</th>
            </tr>
        </thead>
        <tbody>
            @foreach($category->products as $product)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $product->title }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

</x-master>

resources/views/categories/trash.blade.php
<x-master>
    <x-slot:title>
        {{ __('Category List') }}
    </x-slot>

    <x-forms.message />
    <x-forms.errors />

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ __('Categories Trash') }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="{{ route('categories.index') }}">
                <button type="button" class="btn btn-sm btn-outline-primary">
                    <span data-feather="list"></span>
                    {{ __('List') }}
                </button>
            </a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>{{ __('SL#') }}</th>
                <th>{{ __('Title') }}</th>
                <th>{{ __('Action') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($categories as $category)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $category->title }}</td>
                <td>
                    <a class="btn btn-sm btn-info" href="{{ route('categories.show', $category->id) }}">Show</a>
                    <a class="btn btn-sm btn-warning" href="{{ route('categories.restore', $category->id) }}">Restore</a>
                    <form action="{{ route('categories.delete', $category->id) }}" method="post" style="display:inline">
                        @csrf
                        @method('delete')
                        <button class="btn btn-sm btn-danger" onclick="return confirm('Are you sure want to delete')" title="Permanent Delete">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</x-master>