routes/web.php
<?php

use App\Http\Controllers\CommentController;
use App\Http\Controllers\CarouselController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ColorController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WelcomeController;
use Illuminate\Support\Facades\Route;

// http verb: get, post, put/patch, delete

Route::get('/', [WelcomeController::class, 'welcome']);
Route::get('/caterories/{category}/products', [WelcomeController::class, 'productList'])->name('frontend.products');

Route::get('/products/{product}', [WelcomeController::class, 'productDetails'])->name('frontend.products.show');

Route::get('/my-shopping-cart', [WelcomeController::class, 'shoppingCart'])->name('frontend.cart');

require __DIR__ . '/auth.php';
Route::middleware('auth')->prefix('dashboard')->group(function(){



    Route::post('/products/{product}/comments', [CommentController::class, 'store'])->name('products.comments.store');



    Route::get('/', function () {
        return view('home');
    });
    Route::get('carousels-trash', [CarouselController::class, 'trash'])->name('carousels.trash');
    Route::patch('carousels-trash/{id}', [CarouselController::class, 'restore'])->name('carousels.restore');
    Route::delete('carousels-trash/{id}', [CarouselController::class, 'delete'])->name('carousels.delete');
    Route::resource('carousels', CarouselController::class);

    Route::get('/categories-trash', [CategoryController::class, 'trash'])->name('categories.trash');
    Route::get('/categories/{id}/restore', [CategoryController::class, 'restore'])->name('categories.restore');
    Route::delete('/categories/{id}/delete', [CategoryController::class, 'delete'])->name('categories.delete');
    Route::get('/categories/pdf', [CategoryController::class, 'downloadPdf'])->name('categories.pdf');

    Route::resource('categories', CategoryController::class);

    Route::get('/colors-trash', [ColorController::class, 'trash'])->name('colors.trash');
    Route::get('/colors/{id}/restore', [ColorController::class, 'restore'])->name('colors.restore');
    Route::delete('/colors/{id}/delete', [ColorController::class, 'delete'])->name('colors.delete');
    Route::get('/colors/pdf', [ColorController::class, 'downloadPdf'])->name('colors.pdf');
    Route::resource('colors', ColorController::class);


    Route::get('/products-trash', [ProductController::class, 'trash'])->name('products.trash');
    Route::get('/products/{id}/restore', [ProductController::class, 'restore'])->name('products.restore');
    Route::delete('/products/{id}/delete', [ProductController::class, 'delete'])->name('products.delete');
    Route::get('/products/pdf', [ProductController::class, 'downloadPdf'])->name('products.pdf');
    Route::resource('products', ProductController::class);

    Route::prefix('users')->group(function () {
        Route::get('/', [UserController::class, 'index'])->name('users.index');
        Route::get('/{user}', [UserController::class, 'show'])->name('users.show');
        Route::get('/{user}/change-role', [UserController::class, 'changeRole'])->name('users.change_role');
        Route::patch('/{user}/change-role', [UserController::class, 'updateRole'])->name('users.update_role');
    });

    Route::post('products/{product}/cart', [CartController::class, 'store'])->name('products.cart.store');
});

Route::redirect('/here', '/users');

Route::fallback(function () {
    echo 'Apnar url thik nai';
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory, SoftDeletes;

    // protected $fillable = ['title', 'description', 'price'];
    protected $guarded = [];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function colors()
    {
        return $this->belongsToMany(Color::class);
    }

    public function cart()
    {
        return $this->hasMany(Cart::class);
    }
    public function comments()
    {
        // return $this->hasMany(Comment::class)->orderBy('id','desc');
        return $this->morphMany(Comment::class, 'commentable')->orderBy('id','desc');
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use App\Models\Category;
use App\Models\Color;
use App\Models\Product;
use Image;
use Barryvdh\DomPDF\Facade\Pdf;


class ProductController extends Controller
{
    public function index()
    {
        $products = Product::latest()->paginate(15);
        return view('products.index', compact('products'));
    }

    public function create()
    {
        $categories = Category::pluck('title', 'id')->toArray();
        $colors = Color::pluck('title', 'id')->toArray();

        return view('products.create', compact('categories', 'colors'));
    }

    public function show(Product $product)
    {
        // $products = Product::find($id);
        return view('products.show', compact('product'));
    }

    public function store(ProductRequest $request)
    {
        $requestData = [
            'category_id' => $request->category_id,
            'title' => $request->title,
            'description' => $request->description,
            'price' => $request->price,
            'is_active' => $request->is_active ? true : false,
            'image' => $this->uploadImage($request->file('image'))
        ];

        $product = Product::create($requestData);

        $product->colors()->attach($request->colors);

        return redirect()
            ->route('products.index')
            ->withMessage('Successfully Created');
    }

    public function edit(Product $product)
    {
        $categories = Category::pluck('title', 'id')->toArray();
        $colors = Color::pluck('title', 'id')->toArray();
        $selectedColors = $product->colors()->pluck('id')->toArray();
        return view('products.edit', compact('product', 'categories', 'colors', 'selectedColors'));
    }

    public function update(ProductRequest $request, Product $product)
    {
        // $products = Product::find($id);

        $requestData = [
            'title' => $request->title,
            'category_id' => $request->category_id,
            'description' => $request->description,
            'price' => $request->price,
            'is_active' => $request->is_active ? true : false,
        ];

        if ($request->hasFile('image')) {
            $requestData['image'] = $this->uploadImage($request->file('image'));
        }

        $product->update($requestData);
        $product->colors()->sync($request->colors);

        return redirect()
            ->route('products.index')
            ->withMessage('Successfully Updated');
    }

    public function downloadPdf()
    {
        $products = Product::all();
        $pdf = Pdf::loadView('products.pdf', compact('products'));
        return $pdf->download('product-list.pdf');
    }

    public function destroy(Product $product)
    {
        // $products = Product::find($id);
        $product->delete();
        
        // Session::flash('message', 'Successfully deleted');
        // return redirect()
        //         ->route('products.index')
        //         ->with('message', 'Successfully deleted');

        return redirect()
            ->route('products.index')
            ->withMessage('Successfully deleted');
    }

    public function trash()
    {
        $products = Product::onlyTrashed()->get();
        return view('products.trash', compact('products'));
    }

    public function restore($id)
    {
        $products = Product::onlyTrashed()->find($id);
        $products->restore();

        return redirect()
            ->route('products.trash')
            ->withMessage('Successfully restored');
    }

    public function delete($id)
    {
        $product = Product::onlyTrashed()->find($id);
        $product->forceDelete();
        $product->colors()->detach();

        return redirect()
            ->route('products.trash')
            ->withMessage('Successfully deleted');
    }

    public function uploadImage($image)
    {
        $originalName = $image->getClientOriginalName();
        $fileName = date('Y-m-d') . time() . $originalName;

        // $image->move(storage_path('/app/public/products'), $fileName); 

        Image::make($image)
            ->resize(200, 200)
            ->save(storage_path() . '/app/public/products/' . $fileName);

        return $fileName;
    }
}

resources/views/products/create.blade.php
<x-master>
    <x-slot:title>
        {{ __('Product Create') }}
        </x-slot>

        <x-forms.message />

        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">{{ __('Products') }}</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <a href="{{ route('products.index') }}">
                    <button type="button" class="btn btn-sm btn-outline-info">
                        <span data-feather="list"></span>
                        {{ __('List') }}
                    </button>
                </a>
            </div>
        </div>

        <x-forms.errors />

        <form 
            action="{{ route('products.store') }}" 
            method="post" 
            enctype="multipart/form-data">
            @csrf

            <x-forms.select 
                name="category_id" 
                required
                label="Category"
                :options="$categories"
            />

            <x-forms.input 
                type="text" 
                name="title" 
                placeholder="Enter title" 
                required
                label="Title"
            />

            <x-forms.input type="number" name="price" label='Unit Price' />

            <x-forms.input type="file" name="image" label='Picture' />

            <x-forms.textarea name="description" label="Description" />

            <x-forms.checkbox name="colors[]" id="color" :checklist="$colors" label="Colors" />

            @php
                $checklist = ['1'=>'Is Active'];
            @endphp

            <x-forms.checkbox name="is_active" id="is_active" :checklist="$checklist" />

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

</x-master>

resources/views/products/edit.blade.php
<x-master>
    <x-slot:title>
        Product Create
    </x-slot>

    <x-forms.message />

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ __('Products') }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="{{ route('products.index') }}">
                <button type="button" class="btn btn-sm btn-outline-info">
                    <span data-feather="list"></span>
                    {{ __('List') }}
                </button>
            </a>
        </div>
    </div>

    <x-forms.errors />

    <form 
        action="{{ route('products.update', $product->id) }}" 
        method="post" 
        enctype="multipart/form-data">
        @csrf
        @method('patch')

        <x-forms.select name="category_id" required label="Category" :selected="old('category_id', $product->category_id)" :options="$categories" />

        <x-forms.input type="text" name="title" :value="old('title', $product->title)" placeholder="Enter title" required label="Title" />

        <x-forms.input type="number" name="price" label='Unit Price' :value="old('price', $product->price)" />

        <x-forms.input type="file" name="image" label='Picture' />

        <x-forms.textarea name="description" label="Description" :value="old('description', $product->description)" />

        <x-forms.checkbox 
            name="colors[]" 
            id="color" 
            :checklist="$colors" 
            :checkedItems="$selectedColors"
            label="Colors" />

        @php
            $checklist = ['1'=>'Is Active'];

            $checkedItems = [$product->is_active];

        @endphp

        <x-forms.checkbox 
        name="is_active" 
        id="is_active" 
        :checklist="$checklist"
        :checkedItems="$checkedItems"
        />

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

</x-master>

resources/views/products/index.blade.php
<x-master>
    <x-slot:title>
        Product List
    </x-slot>

    <x-forms.message />
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Products</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <a href="{{ route('products.pdf') }}">
                <button type="button" class="btn btn-sm btn-outline-secondary">PDF</button>
                </a>
                <button type="button" class="btn btn-sm btn-outline-secondary">Excel</button>
                <a href="{{ route('products.trash') }}">
                    <button type="button" class="btn btn-sm btn-outline-danger">Trash</button>
                </a>
            </div>
            <a href="{{ route('products.create') }}">
                <button type="button" class="btn btn-sm btn-outline-primary">
                    <span data-feather="plus"></span>
                    Add New
                </button>
            </a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>SL#</th>
                <th>Title</th>
                <th width="180">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach($products as $product)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $product->title }}</td>
                <td>
                    <a class="btn btn-sm btn-info" href="{{ route('products.show', $product->id) }}">Show</a>
                    <a class="btn btn-sm btn-warning" href="{{ route('products.edit', $product->id) }}">Edit</a>
                    <form action="{{ route('products.destroy', $product->id) }}" method="post" style="display:inline">
                        @csrf
                        @method('delete')
                        <button class="btn btn-sm btn-danger" onclick="return confirm('Are you sure want to delete')">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    {{ $products->links() }}
</x-master>

resources/views/products/pdf.blade.php
<table>
    <thead>
        <tr>
            <th>SL#</th>
            <th>Title</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach($categories as $category)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $category->title }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

resources/views/products/show.blade.php
<x-master>
    <x-slot:title>
        Product Details
    </x-slot>
    
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Product</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="{{ route('products.index') }}">
                <button type="button" class="btn btn-sm btn-outline-primary">
                    <span data-feather="list"></span>
                    List
                </button>
            </a>
        </div>
    </div>

    <p>Category: {{ $product->category->title }}</p>
    <h1>Title: {{ $product->title }}</h1>
    <p>Price:{{ $product->price }}</p>
    <p>Description:{{ $product->description }}</p>
    <img src="{{ asset('storage/products/'.$product->image) }}" />

    <p>Colors: 
        <ol>
        @foreach($product->colors as $color)
            <li>{{ $color->title }}</li>
        @endforeach
        </ol>
    </p>

    <p>Is Active ?: {{ $product->is_active ? 'Yes' : 'No' }}</p>

</x-master>

resources/views/products/trash.blade.php
<x-master>
    <x-slot:title>
        {{ __('Category List') }}
    </x-slot>

    <x-forms.message />
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ __('Categories Trash') }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="{{ route('categories.index') }}">
                <button type="button" class="btn btn-sm btn-outline-primary">
                    <span data-feather="list"></span>
                    {{ __('List') }}
                </button>
            </a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>{{ __('SL#') }}</th>
                <th>{{ __('Title') }}</th>
                <th>{{ __('Action') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($categories as $category)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $category->title }}</td>
                <td>
                    <a class="btn btn-sm btn-info" href="{{ route('categories.show', $category->id) }}">Show</a>
                    <a class="btn btn-sm btn-warning" href="{{ route('categories.restore', $category->id) }}">Restore</a>
                    <form action="{{ route('categories.delete', $category->id) }}" method="post" style="display:inline">
                        @csrf
                        @method('delete')
                        <button class="btn btn-sm btn-danger" onclick="return confirm('Are you sure want to delete')" title="Permanent Delete">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</x-master>